name: Check FOSSBilling Compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    name: PHPStan - FOSSBilling Preview
    steps:
      - uses: actions/checkout@v3

      - name: Checkout FOSSBilling Source Code
        uses: actions/checkout@v3
        with:
          repository: "FOSSBilling/FOSSBilling"
          path: "FOSSBilling"

      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          args: --working-dir=FOSSBilling
          dev: no

      - name: Run PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: latest
          configuration: phpstan.neon
          memory_limit: 512M

  phpstan-release:
    runs-on: ubuntu-latest

    name: PHPStan - FOSSBilling Release
    steps:
      - uses: actions/checkout@v3

      - name: Get the Latest FOSSBilling Release Tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: "FOSSBilling/FOSSBilling"
          releases-only: true
        id: get_id

      - name: Checkout The Release tag
        uses: actions/checkout@v3
        with:
          repository: "FOSSBilling/FOSSBilling"
          path: "FOSSBilling"
          ref: ${{ steps.get_id.outputs.tag }}

      - name: Install Composer Dependencies (<=0.4.x)
        if: ${{ hashFiles('FOSSBilling/src/composer.json') }}
        uses: php-actions/composer@v6
        with:
          args: --working-dir=FOSSBilling/src
          dev: no

      - name: Install Composer Dependencies (>=0.5.0)
        if: ${{ hashFiles('FOSSBilling/composer.json') }}
        uses: php-actions/composer@v6
        with:
          args: --working-dir=FOSSBilling/
          dev: no

      - name: Run PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: latest
          configuration: phpstan.neon
          memory_limit: 512M
